### ISSUE TITLE
Items invisible with Shaders (Oculus mod) 1.18.2

### ISSUE THREAD

**Issue by 5stigma** [RogoShum/magickCore#1]
Items invisible with Shaders (Oculus mod)

**Comment by RogoShum** [comment]
I am not sure what version of Minecraft you are using, so I prioritized updating to version 1.18.2. You can use the mod version 0.8.7.

**Comment by 5stigma** [comment]
srry, in 1.18.2 version, forge 40.2.1, and oculus 1.4.3a

**Comment by RogoShum** [comment]
> srry, in 1.18.2 version, forge 40.2.1, and oculus 1.4.3a

Then you should try the 0.8.7 version, I have uploaded it on curseforge

**Comment by 5stigma** [comment]
ok, I will test and report if I find any issues.

**Comment by 5stigma** [comment]
some things were fixed, but others were not
![Shaders issue Magikcore](https://user-images.githubusercontent.com/107163556/232266059-6f611f42-c95f-4a7c-b2a6-b6e2638a9c4e.png)

**Comment by 5stigma** [comment]
The block causes a transparency anywhere I place it.

until now, I realized it just happens with the Element Wool's blocks.

**Comment by RogoShum** [comment]
The new version has fixed some transparency issues(0.8.8), but still has some rendering problems, I will fully fix it in the next version
